### ISSUE TITLE
Move label to title leads to misunderstanding

### ISSUE THREAD

**Issue by nqb** [ltb-project/white-pages#41]
Hello @coudot,

Since 7507aa9, we lost "contains" text in Advanced search in place of a tooltip. I think this is less clear for end users : 
![label_title](https://user-images.githubusercontent.com/10830260/38543342-a43ebd94-3ca4-11e8-8c22-e479386dd9a9.png)

Before 7507aa9 : 
![label](https://user-images.githubusercontent.com/10830260/38543577-2e388aa2-3ca5-11e8-8c02-edda9f878b15.png)

I don't understand your choice.

Maybe we can find a compromise between two solutions.

**Comment by coudot** [comment]
I removed the label because I found it was not esthetic. I just pushed a commit to use a popover, in which we can set a longer text. If you have an idea on how to improve the text, please tell me.
![screenshot_20180411_230227](https://user-images.githubusercontent.com/883396/38643250-d0519f94-3ddc-11e8-828b-5abd13a7f568.png)

**Comment by nqb** [comment]
Ok for popover. For text, what do you think about "Recherche stricte si non cochée".

To be honest, I prefered code with label : simple and stupid.

**Comment by coudot** [comment]
Maybe it would be easier to invert the feature: by default we do substring match, and we check the box only if we need exact matching. What do you think?

**Comment by nqb** [comment]
Great idea, more user-friendly.

**Comment by nqb** [comment]
@coudot,

In that case, we should set `$quick_search_use_substring_match = true;` as default value for Quick Search to be coherent.

**Comment by coudot** [comment]
Done.
